#! /usr/bin/python3

from argparse import ArgumentParser, FileType
import json
from sys import stdin

parser = ArgumentParser()
parser.add_argument("json", nargs='?', type=FileType('r'), default=stdin)
cfg = parser.parse_args()

j = json.load(cfg.json)

print("<gallery>")
for e in j["elements"]:
    wc = e.get("tags", {}).get("wikimedia_commons")
    if wc != None and wc.startswith("File:"):
        osm_type = e["type"]
        osm_id = e["id"]
        print(f"{wc}|[https://www.openstreetmap.org/{osm_type}/{osm_id} {osm_type} {osm_id}]")
print("</gallery>")
