#! /usr/bin/python3

from argparse import ArgumentParser, FileType
import json
import re
from sys import stdin
from urllib.parse import urlencode

parser = ArgumentParser()
parser.add_argument("json", nargs='?', type=FileType('r'), default=stdin)
cfg = parser.parse_args()

j = json.load(cfg.json)

print("<gallery>")
for v in j["data"]:
    if re.match("^File:", v["value"], re.IGNORECASE):
        params = urlencode(dict(key="wikimedia_commons", value=v["value"]))
        tiurl = "https://https://taginfo.openstreetmap.org/tags/?" + params
        print(f"{v['value']}|[{tiurl} {v['count']} use(s)]")
print("</gallery>")
