#! /usr/bin/python3

from argparse import ArgumentParser, FileType
import requests

from usage_bot.osm import from_taginfo, from_overpass

parser = ArgumentParser()
parser.add_argument("--taginfo", action='store_true')
parser.add_argument("--overpass", action='store_true')
cfg = parser.parse_args()

session = requests

if cfg.taginfo:
    files = from_taginfo(session)
elif cfg.overpass:
    files = from_overpass(session)

print("<gallery>")
for filename, caption in sorted(files.items()):
    print(f"{filename}|{caption}")
print("</gallery>")
