#! /usr/bin/python3

import random
import sys

from usage_bot import from_args

def show_demo(files):
    random.seed(0)
    print(f"This is a sample of 1000 files from a total of {len(files)}.")
    print("<gallery>")
    for f in sorted(random.sample(sorted(files.keys()), 1000)):
        print(f"{f}|{files[f]}")
    print("</gallery>")

def main():
    show_demo(from_args(sys.argv))

main()
