#! /usr/bin/python3

import random
import sys

from usage_bot import from_args

def show_demo(files):
    random.seed(0)
    sample = sorted(files.keys())
    if len(sample) > 1000:
        sample = sorted(random.sample(sample, 1000))
        print(f"This is a sample of 1000 files from a total of {len(files)}.")
    else:
        print(f"These are all {len(sample)} files.")
    print("<gallery>")
    for f in sample:
        print(f"{f}|{files[f]}")
    print("</gallery>")

def main():
    show_demo(from_args(sys.argv))

main()
