"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://mitglieder.wikimedia.at/
  name = wmat

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'wmat'
    langs = {
        'de': 'mitglieder.wikimedia.at',
    }

    def scriptpath(self, code):
        return {
            'de': '/w',
        }[code]

    def protocol(self, code):
        return {
            'de': 'https',
        }[code]
