"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://old.wikimedia.cz/wiki/
  name = wmczold

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'wmczold'
    langs = {
        'cs': 'old.wikimedia.cz',
    }

    def scriptpath(self, code):
        return {
            'cs': '/mw',
        }[code]

    def protocol(self, code):
        return {
            'cs': 'https',
        }[code]
