"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://wikimedia.hu/wiki/
  name = wmhu

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'wmhu'
    langs = {
        'hu': 'wikimedia.hu',
    }

    def scriptpath(self, code):
        return {
            'hu': '/w',
        }[code]

    def protocol(self, code):
        return {
            'hu': 'https',
        }[code]
